let menuHTML = "<div class=\"display_menu\"><header class=\"menu_header\"><div class=\"menu_header_top\"><img src=\"Images/Icons/menu.png\" class=\"menu_header_img\"><div class=\"menu_header_adress\"><img src=\"Images/Icons/marker.png\" class=\"menu_header_img\"><span class=\"menu_header_bold\">New York, <span class=\"menu_header_gray\">USA</span></span></div><button class=\"menu_btn_user\" id=\"menu_btn_user\"><img src=\"Images/user.png\" class=\"menu_header_user\"></button></div><div class=\"menu_search\"><input type=\"search\" id=\"search\" name=\"search\" placeholder=\"Search your food here\"><button id=\"menu_header_settings\"><img src=\"Images/Icons/settings.png\" class=\"menu_header_img\"></button></div></header><main class=\"menu_main\"><h2 class=\"menu_h2\">Categories</h2><div class=\"menu_categories\"><div class=\"menu_categories_row\"><button  class=\"menu_main_btn\" id=\"menu_btn_fast_food\"><img src=\"Images/Categories/burger.png\" class=\"menu_main_img\"><span class=\"menu_main_span\">Fast Food</span></button><button  class=\"menu_main_btn\" id=\"menu_btn_italian_food\"><img src=\"Images/Categories/pasta.png\" class=\"menu_main_img\"><span class=\"menu_main_span\">Italian food</span></button></div><div class=\"menu_categories_row\"><button class=\"menu_main_btn\" id=\"menu_btn_japanese_food\"><img src=\"Images/Categories/sushi.png\" class=\"menu_main_img\"><span class=\"menu_main_span\">Japanese food</span></button><button class=\"menu_main_btn\" id=\"menu_btn_vegetarian\"><img src=\"Images/Categories/ratatouille.png\" class=\"menu_main_img\"><span class=\"menu_main_span\">Vegetarian</span></button></div><div class=\"menu_categories_row\"><button class=\"menu_main_btn\" id=\"menu_btn_barbecue\"><img src=\"Images/Categories/chicken.png\" class=\"menu_main_img\"><span class=\"menu_main_span\">Barbecue</span></button><button  class=\"menu_main_btn\" id=\"menu_btn_bakery\"><img src=\"Images/Categories/bread.png\" class=\"menu_main_img\"><span class=\"menu_main_span\">Bakery</span></button></div><div class=\"menu_categories_row menu_categories_last_row_padding\"><button class=\"menu_main_btn\" id=\"menu_btn_desserts\"><img src=\"Images/Categories/parfait.png\" class=\"menu_main_img\"><span class=\"menu_main_span\">Desserts</span></button><button class=\"menu_main_btn\" id=\"menu_btn_beverages\"><img src=\"Images/Categories/boba.png\" class=\"menu_main_img\"><span class=\"menu_main_span\">Beverages</span></button></div></div></main></div>";

let cartHTML = "<div class=\"display_cart\"><div class=\"cart_header\"><h2 class=\"cart_h2\">Your order</h2></div><div class=\"cart_line\"></div><div class=\"cart_item\"><div class=\"cart_item_details\"><span class=\"cart_name_item\">Salad</span><span class=\"cart_price_item\">30$</span><button class=\"btn_delate_item\"><img src=\"Images/Icons/close.png\" class=\"btn_delate_item_img\"></button></div><div class=\"cart_item_line\"></div></div></div>";

let accountHTML = "<div class=\"display_account\"><h2 class=\"account_h2\">My account</h2><img src=\"Images/user.png\" class=\"account_img\"><div class=\"account_line\"></div><div class=\"account_user_data\"><form action=\"\" method=\"post\" name=\"form2\"><label class=\"account_label\" for=\"Name\">Your name and surname</label><br><input class=\"account_input\" type=\"text\" name=\"Name\" id=\"Name\" value=\"Elisabeth Brown\" required><br><br><label class=\"account_label\" for=\"Email\">E-mail</label><br><input class=\"account_input\" type=\"email\" name=\"Email\" id=\"Email\" value=\"lisa_brown@gmail.com\" required><br><br><label class=\"account_label\" for=\"Tel\">Телефон:</label><br><input class=\"account_input\" type=\"tel\" name=\"Tel\" id=\"Tel\" value=\"+1 (415) 555-2671\" required><br><br><label class=\"account_label\" for=\"City\">Your city and country</label><br><input class=\"account_input\" type=\"text\" name=\"City\" id=\"City\" value=\"New York, USA\" required><br><br><label class=\"account_label\" for=\"Adress\">Your adress</label><br><input class=\"account_input\" type=\"text\" name=\"Adress\" id=\"Adress\" value=\"344 2nd Avenue #3\" required></form></div></div>";

let chatHTML = "<div class=\"display_chat\"><h2 class=\"chat_h2\">Contact with us</h2><div class=\"chat_body\"><div class=\"chat_container\"><div class=\"chat\"><div class=\"chat_admin\"><span class=\"chat_span\">Hello! How can I help you?</span></div></div><div class=\"chat_user\"><input id=\"txt\" type=\"text\"><button id=\"chat_btn\">Send</button></div></div></div></div>";

let footerHTML = "<footer class=\"display_footer\"><button class=\"footer_btn\" id=\"footer_btn_menu\"><img src=\"Images/Icons/home.png\" class=\"footer_btn_img\"></button><button class=\"footer_btn\" id=\"footer_btn_chat\"><img src=\"Images/Icons/comment.png\" class=\"footer_btn_img\"></button><button class=\"footer_btn\" id=\"footer_btn_cart\"><img src=\"Images/Icons/shopping-cart.png\" class=\"footer_btn_img\"></button><button class=\"footer_btn\" id=\"footer_btn_account\"><img src=\"Images/Icons/user.png\" class=\"footer_btn_img\"></button></footer>";

let div = document.querySelector('.container');